In [135]:
import codecs
import pandas as pd
import numpy as np
import csv
from StringIO import StringIO
from datetime import datetime

In [33]:
with codecs.open('stoptimes.csv', 'r') as f:
    data = f.read()

In [34]:
stoptimes = pd.read_csv(StringIO(data.replace('"', '')), sep=',', encoding='utf-8', quoting=csv.QUOTE_NONE)

In [54]:
stoptimes.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
0,15.T2.2-ALM-B-mjp-1.1.H,10:49:00,10:49:00,19853,1,NaN,0,0,0.000000
1,15.T2.2-ALM-B-mjp-1.1.H,10:51:00,10:51:00,19852,2,NaN,0,0,1506.610171
2,15.T2.2-ALM-B-mjp-1.1.H,10:53:00,10:53:00,19851,3,NaN,0,0,1992.788001
3,15.T2.2-ALM-B-mjp-1.1.H,10:55:00,10:55:00,19850,4,NaN,0,0,3020.805604
4,15.T2.2-ALM-B-mjp-1.1.H,10:57:00,10:57:00,19849,5,NaN,0,0,3968.143881

In [27]:
stoptimes.dtypes

trip_id                 object
arrival_time            object
departure_time          object
stop_id                  int64
stop_sequence            int64
stop_headsign          float64
pickup_type              int64
drop_off_type            int64
shape_dist_traveled    float64
dtype: object

In [47]:
with codecs.open('stops.csv', 'r') as f:
    data2 = f.read()
stops = pd.read_csv(StringIO(data2.replace('"', '')), sep=',', encoding='utf-8', quoting=csv.QUOTE_NONE)
stops.dtypes
stops.head()

   stop_id                                    stop_name   stop_lat    stop_lon
0    15351            Sunbury Railway Station (Sunbury) -37.579091  144.727319
1    15353  Diggers Rest Railway Station (Diggers Rest) -37.627017  144.719922
2    19827     Stony Point Railway Station (Crib Point) -38.374235  145.221837
3    19828      Crib Point Railway Station (Crib Point) -38.366123  145.204043
4    19829        Morradoo Railway Station (Crib Point) -38.354033  145.189602

In [44]:
type(stoptimes)

pandas.core.frame.DataFrame

In [46]:
# Merge https://chrisalbon.com/python/data_wrangling/pandas_join_merge_dataframe/
from IPython.display import display
from IPython.display import Image

In [78]:
merged = pd.merge(stoptimes, stops, on='stop_id', how='inner')
merged.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,stop_name,stop_lat,stop_lon
0,15.T2.2-ALM-B-mjp-1.1.H,10:49:00,10:49:00,19853,1,NaN,0,0,0.0,Camberwell Railway Station (Camberwell),-37.826567,145.058697
1,16.UJ.2-ALM-B-mjp-1.1.H,10:49:00,10:49:00,19853,1,NaN,0,0,0.0,Camberwell Railway Station (Camberwell),-37.826567,145.058697
2,23.T2.2-ALM-B-mjp-1.1.H,11:09:00,11:09:00,19853,1,NaN,0,0,0.0,Camberwell Railway Station (Camberwell),-37.826567,145.058697
3,24.UJ.2-ALM-B-mjp-1.1.H,11:09:00,11:09:00,19853,1,NaN,0,0,0.0,Camberwell Railway Station (Camberwell),-37.826567,145.058697
4,31.T2.2-ALM-B-mjp-1.1.H,11:29:00,11:29:00,19853,1,NaN,0,0,0.0,Camberwell Railway Station (Camberwell),-37.826567,145.058697

In [79]:
# dropped columns https://stackoverflow.com/questions/13411544/delete-column-from-pandas-dataframe-using-del-df-column-name
new = merged.drop(merged.columns[[5, 6, 7,8]], axis=1)
new.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_name,stop_lat,stop_lon
0,15.T2.2-ALM-B-mjp-1.1.H,10:49:00,10:49:00,19853,1,Camberwell Railway Station (Camberwell),-37.826567,145.058697
1,16.UJ.2-ALM-B-mjp-1.1.H,10:49:00,10:49:00,19853,1,Camberwell Railway Station (Camberwell),-37.826567,145.058697
2,23.T2.2-ALM-B-mjp-1.1.H,11:09:00,11:09:00,19853,1,Camberwell Railway Station (Camberwell),-37.826567,145.058697
3,24.UJ.2-ALM-B-mjp-1.1.H,11:09:00,11:09:00,19853,1,Camberwell Railway Station (Camberwell),-37.826567,145.058697
4,31.T2.2-ALM-B-mjp-1.1.H,11:29:00,11:29:00,19853,1,Camberwell Railway Station (Camberwell),-37.826567,145.058697

In [80]:
# reorder columns https://stackoverflow.com/questions/41968732/set-order-of-columns-in-pandas-dataframe/41968825
new = new[['stop_id', 'stop_name', 'arrival_time', 'departure_time', 'trip_id', 'stop_sequence', 'stop_lat', 'stop_lon']]
new

,stop_id,stop_name,arrival_time,departure_time,trip_id,stop_sequence,stop_lat,stop_lon
0,19853,Camberwell Railway Station (Camberwell),10:49:00,10:49:00,15.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
1,19853,Camberwell Railway Station (Camberwell),10:49:00,10:49:00,16.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
2,19853,Camberwell Railway Station (Camberwell),11:09:00,11:09:00,23.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
3,19853,Camberwell Railway Station (Camberwell),11:09:00,11:09:00,24.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
4,19853,Camberwell Railway Station (Camberwell),11:29:00,11:29:00,31.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
5,19853,Camberwell Railway Station (Camberwell),11:29:00,11:29:00,32.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
6,19853,Camberwell Railway Station (Camberwell),11:49:00,11:49:00,39.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
7,19853,Camberwell Railway Station (Camberwell),11:49:00,11:49:00,40.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
8,19853,Camberwell Railway Station (Camberwell),12:09:00,12:09:00,47.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
9,19853,Camberwell Railway Station (Camberwell),12:09:00,12:09:00,48.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
10,19853,Camberwell Railway Station (Camberwell),12:29:00,12:29:00,55.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
11,19853,Camberwell Railway Station (Camberwell),12:29:00,12:29:00,56.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
12,19853,Camberwell Railway Station (Camberwell),12:49:00,12:49:00,63.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
13,19853,Camberwell Railway Station (Camberwell),12:49:00,12:49:00,64.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
14,19853,Camberwell Railway Station (Camberwell),13:09:00,13:09:00,67.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
15,19853,Camberwell Railway Station (Camberwell),13:09:00,13:09:00,68.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
16,19853,Camberwell Railway Station (Camberwell),13:29:00,13:29:00,75.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
17,19853,Camberwell Railway Station (Camberwell),13:29:00,13:29:00,76.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
18,19853,Camberwell Railway Station (Camberwell),13:49:00,13:49:00,83.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
19,19853,Camberwell Railway Station (Camberwell),13:49:00,13:49:00,84.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
20,19853,Camberwell Railway Station (Camberwell),14:09:00,14:09:00,91.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
21,19853,Camberwell Railway Station (Camberwell),14:09:00,14:09:00,92.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
22,19853,Camberwell Railway Station (Camberwell),14:29:00,14:29:00,99.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
23,19853,Camberwell Railway Station (Camberwell),14:29:00,14:29:00,100.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
24,19853,Camberwell Railway Station (Camberwell),14:49:00,14:49:00,105.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
25,19853,Camberwell Railway Station (Camberwell),14:49:00,14:49:00,106.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
26,19853,Camberwell Railway Station (Camberwell),15:09:00,15:09:00,111.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
27,19853,Camberwell Railway Station (Camberwell),15:09:00,15:09:00,112.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
28,19853,Camberwell Railway Station (Camberwell),15:29:00,15:29:00,119.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
29,19853,Camberwell Railway Station (Camberwell),15:29:00,15:29:00,120.UJ.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
...,...,...,...,...,...,...,...,...
437941,20028,Showgrounds Railway Station (Flemington),11:17:00,11:17:00,9128.T2.2-ain-mjp-1.2.R,1,-37.783472,144.914257
437942,20028,Showgrounds Railway Station (Flemington),11:17:00,11:17:00,9129.UJ.2-ain-mjp-1.2.R,1,-37.783472,144.914257
437943,20028,Showgrounds Railway Station (Flemington),11:43:00,11:43:00,9132.T2.2-ain-mjp-1.2.R,1,-37.783472,144.914257
437944,20028,Showgrounds Railway Station (Flemington),11:43:00,11:43:00,9133.UJ.2-ain-mjp-1.2.R,1,-37.783472,144.914257
437945,20028,Showgrounds Railway Station (Flemington),12:43:00,12:43:00,9140.T2.2-ain-mjp-1.2.R,1,-37.783472,144.914257
437946,20028,Showgrounds Railway Station (Flemington),12:43:00,12:43:00,9141.UJ.2-ain-mjp-1.2.R,1,-37.783472,144.914257
437947,20028,Showgrounds Railway Station (Flemington),12:17:00,12:17:00,9136.T2.2-ain-mjp-1.2.R,1,-37.783472,144.914257
437948,20028,Showgrounds Railway Station (Flemington),12:17:00,12:17:00,9137.UJ.2-ain-mjp-1.2.R,1,-37.783472,144.914257
437949,20028,Showgrounds Railway Station (Flemington),13:17:00,13:17:00,9144.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437950,20028,Showgrounds Railway Station (Flemington),13:17:00,13:17:00,9145.UJ.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437951,20028,Showgrounds Railway Station (Flemington),13:47:00,13:47:00,9148.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437952,20028,Showgrounds Railway Station (Flemington),13:47:00,13:47:00,9149.UJ.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437953,20028,Showgrounds Railway Station (Flemington),14:10:00,14:10:00,9152.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437954,20028,Showgrounds Railway Station (Flemington),14:10:00,14:10:00,9153.UJ.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437955,20028,Showgrounds Railway Station (Flemington),14:43:00,14:43:00,9156.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437956,20028,Showgrounds Railway Station (Flemington),14:43:00,14:43:00,9157.UJ.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437957,20028,Showgrounds Railway Station (Flemington),15:17:00,15:17:00,9160.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437958,20028,Showgrounds Railway Station (Flemington),15:17:00,15:17:00,9161.UJ.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437959,20028,Showgrounds Railway Station (Flemington),15:43:00,15:43:00,9164.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437960,20028,Showgrounds Railway Station (Flemington),15:43:00,15:43:00,9165.UJ.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437961,20028,Showgrounds Railway Station (Flemington),16:17:00,16:17:00,9168.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437962,20028,Showgrounds Railway Station (Flemington),16:17:00,16:17:00,9169.UJ.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437963,20028,Showgrounds Railway Station (Flemington),16:43:00,16:43:00,9172.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437964,20028,Showgrounds Railway Station (Flemington),16:43:00,16:43:00,9173.UJ.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437965,20028,Showgrounds Railway Station (Flemington),17:30:00,17:30:00,9180.UJ.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437966,20028,Showgrounds Railway Station (Flemington),17:43:00,17:43:00,9181.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437967,20028,Showgrounds Railway Station (Flemington),18:30:00,18:30:00,9185.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437968,20028,Showgrounds Railway Station (Flemington),17:17:00,17:17:00,9176.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437969,20028,Showgrounds Railway Station (Flemington),17:17:00,17:17:00,9177.UJ.2-ain-mjp-1.3.R,1,-37.783472,144.914257
437970,20028,Showgrounds Railway Station (Flemington),18:17:00,18:17:00,9183.T2.2-ain-mjp-1.3.R,1,-37.783472,144.914257

In [81]:
new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 437971 entries, 0 to 437970
Data columns (total 8 columns):
stop_id           437971 non-null int64
stop_name         437971 non-null object
arrival_time      437971 non-null object
departure_time    437971 non-null object
trip_id           437971 non-null object
stop_sequence     437971 non-null int64
stop_lat          437971 non-null float64
stop_lon          437971 non-null float64
dtypes: float64(2), int64(2), object(4)
memory usage: 30.1+ MB

In [122]:
# https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop_duplicates.html
stoptime = new.drop_duplicates(subset='stop_id', keep='first', inplace=False)
stoptime.shape

(222, 8)

In [131]:
len(Ala)
Ala.arrival_time

0        10:49:00
3567     10:51:00
4869     10:53:00
6161     10:55:00
7453     10:57:00
8745     10:59:00
10037    11:01:00
11329    05:28:00
30327    05:31:00
40280    05:33:00
42105    05:35:00
45418    05:37:00
47338    05:39:00
49763    05:41:00
Name: arrival_time, dtype: object

In [127]:
alamein = ['19853', '19852','19851', '19850', '19849', '19848', '19847', '19906', '19905', '19904', '19903', '19907', '19908','19854']  
Ala = stoptime.loc[stoptime['stop_id'].isin(alamein)]
Ala.sort_values(by = ['arrival_time'])

# indexed = stoptime.set_index(["trip_id","stop_id","stop_name"], inplace = True)
# indexed
# Ala = stoptime.loc[stoptime['trip_id'] == '15.T2.2-ALM-B-mjp-1.1.H']

,stop_id,stop_name,arrival_time,departure_time,trip_id,stop_sequence,stop_lat,stop_lon
11329,19854,Flinders Street Railway Station (Melbourne City),05:28:00,05:28:00,9820.T6.2-ALM-B-mjp-1.2.H,1,-37.818305,144.966964
30327,19908,Richmond Railway Station (Richmond),05:31:00,05:31:00,9820.T6.2-ALM-B-mjp-1.2.H,2,-37.824074,144.990164
40280,19907,East Richmond Railway Station (Richmond),05:33:00,05:33:00,9820.T6.2-ALM-B-mjp-1.2.H,3,-37.826400,144.997066
42105,19906,Burnley Railway Station (Burnley),05:35:00,05:35:00,9820.T6.2-ALM-B-mjp-1.2.H,4,-37.827560,145.007555
45418,19905,Hawthorn Railway Station (Hawthorn),05:37:00,05:37:00,9820.T6.2-ALM-B-mjp-1.2.H,5,-37.821826,145.022899
47338,19904,Glenferrie Railway Station (Hawthorn),05:39:00,05:39:00,9820.T6.2-ALM-B-mjp-1.2.H,6,-37.821467,145.036439
49763,19903,Auburn Railway Station (Hawthorn East),05:41:00,05:41:00,9820.T6.2-ALM-B-mjp-1.2.H,7,-37.822398,145.045844
0,19853,Camberwell Railway Station (Camberwell),10:49:00,10:49:00,15.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
3567,19852,Riversdale Railway Station (Camberwell),10:51:00,10:51:00,15.T2.2-ALM-B-mjp-1.1.H,2,-37.831505,145.069646
4869,19851,Willison Railway Station (Camberwell),10:53:00,10:53:00,15.T2.2-ALM-B-mjp-1.1.H,3,-37.835716,145.070298
6161,19850,Hartwell Railway Station (Camberwell),10:55:00,10:55:00,15.T2.2-ALM-B-mjp-1.1.H,4,-37.843985,145.075560
7453,19849,Burwood Railway Station (Glen Iris),10:57:00,10:57:00,15.T2.2-ALM-B-mjp-1.1.H,5,-37.851563,145.080511
8745,19848,Ashburton Railway Station (Ashburton),10:59:00,10:59:00,15.T2.2-ALM-B-mjp-1.1.H,6,-37.861968,145.081344
10037,19847,Alamein Railway Station (Ashburton),11:01:00,11:01:00,15.T2.2-ALM-B-mjp-1.1.H,7,-37.868320,145.079656

In [109]:
stoptime[2:35]

,stop_id,stop_name,arrival_time,departure_time,trip_id,stop_sequence,stop_lat,stop_lon
4869,19851,Willison Railway Station (Camberwell),10:53:00,10:53:00,15.T2.2-ALM-B-mjp-1.1.H,3,-37.835716,145.070298
6161,19850,Hartwell Railway Station (Camberwell),10:55:00,10:55:00,15.T2.2-ALM-B-mjp-1.1.H,4,-37.843985,145.075560
7453,19849,Burwood Railway Station (Glen Iris),10:57:00,10:57:00,15.T2.2-ALM-B-mjp-1.1.H,5,-37.851563,145.080511
8745,19848,Ashburton Railway Station (Ashburton),10:59:00,10:59:00,15.T2.2-ALM-B-mjp-1.1.H,6,-37.861968,145.081344
10037,19847,Alamein Railway Station (Ashburton),11:01:00,11:01:00,15.T2.2-ALM-B-mjp-1.1.H,7,-37.868320,145.079656
11329,19854,Flinders Street Railway Station (Melbourne City),05:28:00,05:28:00,9820.T6.2-ALM-B-mjp-1.2.H,1,-37.818305,144.966964
30327,19908,Richmond Railway Station (Richmond),05:31:00,05:31:00,9820.T6.2-ALM-B-mjp-1.2.H,2,-37.824074,144.990164
40280,19907,East Richmond Railway Station (Richmond),05:33:00,05:33:00,9820.T6.2-ALM-B-mjp-1.2.H,3,-37.826400,144.997066
42105,19906,Burnley Railway Station (Burnley),05:35:00,05:35:00,9820.T6.2-ALM-B-mjp-1.2.H,4,-37.827560,145.007555
45418,19905,Hawthorn Railway Station (Hawthorn),05:37:00,05:37:00,9820.T6.2-ALM-B-mjp-1.2.H,5,-37.821826,145.022899
47338,19904,Glenferrie Railway Station (Hawthorn),05:39:00,05:39:00,9820.T6.2-ALM-B-mjp-1.2.H,6,-37.821467,145.036439
49763,19903,Auburn Railway Station (Hawthorn East),05:41:00,05:41:00,9820.T6.2-ALM-B-mjp-1.2.H,7,-37.822398,145.045844
51683,19843,Parliament Railway Station (Melbourne City),05:30:00,05:30:00,9822.T6.2-ALM-B-mjp-1.3.H,1,-37.811054,144.972911
62374,19842,Melbourne Central Railway Station (Melbourne C...,05:32:00,05:32:00,9822.T6.2-ALM-B-mjp-1.3.H,2,-37.809939,144.962594
73065,19841,Flagstaff Railway Station (Melbourne City),05:33:00,05:33:00,9822.T6.2-ALM-B-mjp-1.3.H,3,-37.811981,144.955654
83756,22180,Southern Cross Railway Station (Melbourne City),05:35:00,05:35:00,9822.T6.2-ALM-B-mjp-1.3.H,4,-37.817936,144.951411
96612,19973,North Melbourne Railway Station (West Melbourne),25:51:00,25:51:00,3969.T6.2-B31-C-mjp-1.1.H,3,-37.806310,144.941510
103007,20041,Kensington Railway Station (Kensington),25:53:00,25:53:00,3969.T6.2-B31-C-mjp-1.1.H,4,-37.793780,144.930524
104494,20040,Newmarket Railway Station (Flemington),25:55:00,25:55:00,3969.T6.2-B31-C-mjp-1.1.H,5,-37.787328,144.928978
105981,20039,Ascot Vale Railway Station (Ascot Vale),25:57:00,25:57:00,3969.T6.2-B31-C-mjp-1.1.H,6,-37.775306,144.921821
107484,20038,Moonee Ponds Railway Station (Moonee Ponds),25:59:00,25:59:00,3969.T6.2-B31-C-mjp-1.1.H,7,-37.765707,144.919161
108987,20037,Essendon Railway Station (Essendon),26:01:00,26:01:00,3969.T6.2-B31-C-mjp-1.1.H,8,-37.756012,144.916198
110683,20036,Glenbervie Railway Station (Essendon),26:03:00,26:03:00,3969.T6.2-B31-C-mjp-1.1.H,9,-37.747210,144.920939
112379,20035,Strathmore Railway Station (Strathmore),26:04:00,26:04:00,3969.T6.2-B31-C-mjp-1.1.H,10,-37.743591,144.927316
114075,20034,Pascoe Vale Railway Station (Pascoe Vale),26:06:00,26:06:00,3969.T6.2-B31-C-mjp-1.1.H,11,-37.730756,144.928196
115771,20033,Oak Park Railway Station (Oak Park),26:09:00,26:09:00,3969.T6.2-B31-C-mjp-1.1.H,12,-37.717950,144.921519
117467,20032,Glenroy Railway Station (Glenroy),26:11:00,26:11:00,3969.T6.2-B31-C-mjp-1.1.H,13,-37.704536,144.917220
119163,20031,Jacana Railway Station (Glenroy),26:13:00,26:13:00,3969.T6.2-B31-C-mjp-1.1.H,14,-37.695131,144.915851
120377,20030,Broadmeadows Railway Station (Broadmeadows),26:15:00,26:15:00,3969.T6.2-B31-C-mjp-1.1.H,15,-37.683049,144.919613
122518,44817,Coolaroo Railway Station (Coolaroo),26:18:00,26:18:00,3969.T6.2-B31-C-mjp-1.1.H,16,-37.661003,144.926056
124141,40220,Roxburgh Park Railway Station (Roxburgh Park),26:22:00,26:22:00,3969.T6.2-B31-C-mjp-1.1.H,17,-37.638231,144.935404
125764,40221,Craigieburn Railway Station (Craigieburn),26:26:00,26:26:00,3969.T6.2-B31-C-mjp-1.1.H,18,-37.601817,144.943320
127387,20027,Flemington Racecourse Railway Station (Fleming...,05:25:00,05:25:00,8608.UO.2-B31-G-mjp-1.2.H,1,-37.787202,144.907589

In [108]:
stoptime.loc[stoptime['stop_name'] == 'Auburn Railway Station (Hawthorn East)']

,stop_id,stop_name,arrival_time,departure_time,trip_id,stop_sequence,stop_lat,stop_lon
49763,19903,Auburn Railway Station (Hawthorn East),05:41:00,05:41:00,9820.T6.2-ALM-B-mjp-1.2.H,7,-37.822398,145.045844

In [132]:
Ala['arrival_time'] = pd.to_datetime(Ala['arrival_time'], format='%H:%M:%S')

C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [133]:
Ala

,stop_id,stop_name,arrival_time,departure_time,trip_id,stop_sequence,stop_lat,stop_lon
0,19853,Camberwell Railway Station (Camberwell),1900-01-01 10:49:00,10:49:00,15.T2.2-ALM-B-mjp-1.1.H,1,-37.826567,145.058697
3567,19852,Riversdale Railway Station (Camberwell),1900-01-01 10:51:00,10:51:00,15.T2.2-ALM-B-mjp-1.1.H,2,-37.831505,145.069646
4869,19851,Willison Railway Station (Camberwell),1900-01-01 10:53:00,10:53:00,15.T2.2-ALM-B-mjp-1.1.H,3,-37.835716,145.070298
6161,19850,Hartwell Railway Station (Camberwell),1900-01-01 10:55:00,10:55:00,15.T2.2-ALM-B-mjp-1.1.H,4,-37.843985,145.075560
7453,19849,Burwood Railway Station (Glen Iris),1900-01-01 10:57:00,10:57:00,15.T2.2-ALM-B-mjp-1.1.H,5,-37.851563,145.080511
8745,19848,Ashburton Railway Station (Ashburton),1900-01-01 10:59:00,10:59:00,15.T2.2-ALM-B-mjp-1.1.H,6,-37.861968,145.081344
10037,19847,Alamein Railway Station (Ashburton),1900-01-01 11:01:00,11:01:00,15.T2.2-ALM-B-mjp-1.1.H,7,-37.868320,145.079656
11329,19854,Flinders Street Railway Station (Melbourne City),1900-01-01 05:28:00,05:28:00,9820.T6.2-ALM-B-mjp-1.2.H,1,-37.818305,144.966964
30327,19908,Richmond Railway Station (Richmond),1900-01-01 05:31:00,05:31:00,9820.T6.2-ALM-B-mjp-1.2.H,2,-37.824074,144.990164
40280,19907,East Richmond Railway Station (Richmond),1900-01-01 05:33:00,05:33:00,9820.T6.2-ALM-B-mjp-1.2.H,3,-37.826400,144.997066
42105,19906,Burnley Railway Station (Burnley),1900-01-01 05:35:00,05:35:00,9820.T6.2-ALM-B-mjp-1.2.H,4,-37.827560,145.007555
45418,19905,Hawthorn Railway Station (Hawthorn),1900-01-01 05:37:00,05:37:00,9820.T6.2-ALM-B-mjp-1.2.H,5,-37.821826,145.022899
47338,19904,Glenferrie Railway Station (Hawthorn),1900-01-01 05:39:00,05:39:00,9820.T6.2-ALM-B-mjp-1.2.H,6,-37.821467,145.036439
49763,19903,Auburn Railway Station (Hawthorn East),1900-01-01 05:41:00,05:41:00,9820.T6.2-ALM-B-mjp-1.2.H,7,-37.822398,145.045844

In [134]:
Ala.arrival_time.diff()

0                     NaT
3567             00:02:00
4869             00:02:00
6161             00:02:00
7453             00:02:00
8745             00:02:00
10037            00:02:00
11329   -1 days +18:27:00
30327            00:03:00
40280            00:02:00
42105            00:02:00
45418            00:02:00
47338            00:02:00
49763            00:02:00
Name: arrival_time, dtype: timedelta64[ns]